name: Output information
on:
  pull_request:
    types:
      - opened
      - closed
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*'
      - 'feat/**'
    paths:
      - '.github/workflows/output.yml'
    paths-ignore:
      - 'README.md'
jobs:
  info:
    runs-on: ubuntu-22.04
    steps:
      - name: Output Github context
        run: 'echo "GitHub context: ${{ toJson(github) }}"'
